application: imokapp
version: 1
runtime: python
api_version: 1

handlers:

- url: /static/css
  static_dir: static/css
  mime_type: text/css

- url: /static/js
  static_dir: static/js
  mime_type: text/javascript

- url: /static/img
  static_dir: static/img
  mime_type: image/png

- url: /static/pdf
  static_dir: static/pdf
  mime_type: application/pdf

- url: /incoming/.*
  script: incoming.py

- url: /phone/.*
  script: phone.py

- url: /tasks/.*
  script: tasks.py
  login: admin

- url: /newuser/.*
  script: newuser.py

- url: .*
  script: main.py
